
How big are they?

```{r shape}
ggplot(socrata) + aes(x = ncol, y = nrow, size = downloadCount, color = portal) + geom_point()
```

A bunch have no rows nor columns.

```
Plot here
```

What are their column types?

```{r ncol}
socrata.column.types <- subset(melt(socrata), strtrim(variable, 5) == 'ncol.')
ggplot(socrata.column.types) +
  aes(group = paste(portal, id), y = variable, x = value, color = portal) +
  geom_path()
```

```{r}
# Bin the minority types
socrata.column.types$variable <-
  factor(socrata.column.types$variable, levels = c(
    "ncol.calendar_date", "ncol.checkbox",
    "ncol.dataset_link", "ncol.date",
    "ncol.document", "ncol.document_obsolete",
    "ncol.drop_down_list", "ncol.email",
    "ncol.flag", "ncol.geospatial",
    "ncol.html", "ncol.list",
    "ncol.location", "ncol.money",
    "ncol.nested_table", "ncol.number",
    "ncol.object", "ncol.percent",
    "ncol.phone", "ncol.photo",
    "ncol.photo_obsolete", "ncol.stars",
    "ncol.text", "ncol.url"
  ))
levels(socrata.column.types$variable) <- c(
  "ncol.other", "ncol.checkbox",
  "ncol.other", "ncol.date",
  "ncol.other", "ncol.other",
  "ncol.drop_down_list", "ncol.other",
  "ncol.other", "ncol.other",
  "ncol.html", "ncol.other",
  "ncol.other", "ncol.money",
  "ncol.other", "ncol.number",
  "ncol.other", "ncol.percent",
  "ncol.other", "ncol.photo",
  "ncol.other", "ncol.stars",
  "ncol.text", "ncol.url"
))
```

Datasets with lots of rows:

  socrata[order(socrata$ncol, decreasing = T),][1:40,c('portal','id','nrow','ncol','downloadCount')]

We should reshape these.

https://data.illinois.gov/Transportation/IDOT-Published-For-The-Record-2011-Spot-Improvemen/ss2t-nnma?

